name = "Bistro"
author = "AdriaAyl"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c9ef35dc531e896a8d215c022f47e3f1070fedb2231958bfe5e340207abfcc8"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
