name = "Bistro"
author = "AdriaAyl"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a50e81274a47f2553ba6b4be97fb573349368d4291289e6c6abf7ac61615745"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
