name = "Bistro"
author = "AdriaAyl"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f5afb89d111bd135ff7b50164e689ac043e0d355bb32d737eb5d6b8c4b54834"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
